;;; blackbored-theme --- pretty colours
;;; Commentary:
;;; Code:
(deftheme blackbored)
(custom-theme-set-faces
 'blackbored
 '(default                                ((t (:background "#000000" :foreground "#e5e5e5"))))
 '(bold                                   ((t (:box (:line-width (2 . 2) :color "#333333" :style flat-button) :weight bold))))
 '(mode-line                              ((t (:background "#333333" :foreground "#20d030"))))
 '(mode-line-inactive                     ((t (:background "#1a1a1a" :foreground "#4d4d4d"))))
 '(vertical-border                        ((t (:foreground "#1a1a1a"))))
 '(hl-line                                ((t (:background "#151515"))))
 '(diary                                  ((t (:foreground "#ffa500"))))
 '(font-lock-builtin-face                 ((t (:foreground "#4c83ff"))))
 '(font-lock-comment-face                 ((t (:foreground "#8a8a8a"))))
 '(font-lock-constant-face                ((t (:foreground "#D8FA3C"))))
 '(font-lock-doc-string-face              ((t (:foreground "#ff8c00"))))
 '(font-lock-function-name-face           ((t (:foreground "#cd00cd"))))
 '(font-lock-keyword-face                 ((t (:foreground "#FBDE2D"))))
 '(font-lock-preprocessor-face            ((t (:foreground "#919191"))))
 '(font-lock-reference-face               ((t (:foreground "#bebebe"))))
 '(font-lock-regexp-grouping-backslash    ((t (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct    ((t (:foreground "#cd0000"))))
 '(font-lock-string-face                  ((t (:foreground "#61CE3C"))))
 '(font-lock-type-face                    ((t (:foreground "#E00000"))))
 '(font-lock-variable-name-face           ((t (:foreground "#FF6400"))))
 '(font-lock-warning-face                 ((t (:foreground "#ffc0cb"))))
 '(font-lock-doc-face                     ((t (:foreground "#61CE3C"))))
 '(region                                 ((t (:background "#7F073F"))))
 '(link                                   ((t (:foreground "#44aaff" :underline t))))
 '(ivy-current-match                      ((t (:background "#666666"))))
 '(popup-face                             ((t (:background "#303030" :foreground "#cdcd00"))))
 '(popup-tip-face                         ((t (:background "#303030" :foreground "#20d020"))))
 '(flycheck-info                          ((t (:underline  "#ffc0cb"))))
 '(highlight-indent-guides-character-face ((t (:foreground "#7f7f7f"))))
 '(term-color-blue                        ((t (:background "#5c5cff" :foreground "#5c5cff"))))
 '(term-color-red                         ((t (:background "#cd0000" :foreground "#cd0000"))))
 '(eshell-ls-executable                   ((t (:foreground "#44aa22" :weight bold))))
 '(success                                ((t (:foreground "#44aa22" :weight bold))))
 '(show-paren-match                       ((t (:background "#3d3d3d"))))
 '(widget-field                           ((t (:background "#212121" :foreground "#ff00ff"))))
 '(custom-variable-tag                    ((t (:foreground "#ff00ff" :weight bold))))
 '(bookmark-face                          ((t (:background "#2f4f4f"))))
 '(lsp-face-highlight-textual             ((t (:background "#204030"))))
 '(secondary-selection                    ((t (:extend t :background "#292929"))))
 '(custom-button                          ((t (:background "#606060" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(warning                                ((t (:foreground "#ff5522"))))

 '(rainbow-delimiters-depth-1-face        ((t (:foreground "#cd0000"))))
 '(rainbow-delimiters-depth-2-face        ((t (:foreground "#006400"))))
 '(rainbow-delimiters-depth-3-face        ((t (:foreground "#ff1493"))))
 '(rainbow-delimiters-depth-4-face        ((t (:foreground "#cdcd00"))))
 '(rainbow-delimiters-depth-5-face        ((t (:foreground "#00cd00"))))
 '(rainbow-delimiters-depth-6-face        ((t (:foreground "#add8e6"))))
 '(rainbow-delimiters-depth-7-face        ((t (:foreground "#ffa500"))))
 '(rainbow-delimiters-depth-8-face        ((t (:foreground "#6a5acd"))))
 '(rainbow-delimiters-depth-9-face        ((t (:foreground "#d3d3d3"))))
 '(rainbow-delimiters-unmatched-face      ((t (:foreground "#e5e5e5"))))

 '(org-level-1                            ((t (:foreground "#80ff00"))))
 '(org-level-2                            ((t (:foreground "#70e000"))))
 '(org-level-3                            ((t (:foreground "#60d000"))))
 '(org-level-4                            ((t (:foreground "#50c800"))))
 '(org-level-5                            ((t (:foreground "#40b000"))))
 '(org-level-6                            ((t (:foreground "#30a000"))))
 '(org-level-7                            ((t (:foreground "#209000"))))
 '(org-level-8                            ((t (:foreground "#108000"))))
 '(org-meta-line                          ((t (:foreground "#4d4d4d"))))

 '(org-agenda-date-today                  ((t (:inherit org-agenda-date :weight bold))))
 
 '(visible-mark-active                    ((t (:background "#d0ffd0"))))
 '(visible-mark-face1                     ((t (:background "#80ff00"))))
 '(visible-mark-face2                     ((t (:background "#70a000"))))
 '(visible-mark-face3                     ((t (:background "#609000"))))
 '(visible-mark-face4                     ((t (:background "#507000"))))
 '(visible-mark-face5                     ((t (:background "#405000"))))
 '(visible-mark-face6                     ((t (:background "#305000"))))
 '(visible-mark-face7                     ((t (:background "#205020"))))
 '(visible-mark-face8                     ((t (:background "#104020"))))

 '(tab-bar                                ((t (:background "#1a1a1a" :foreground "#20d030" :height 1.1))))
 '(tab-bar-tab                            ((t (:inherit tab-bar))))
 '(tab-bar-tab-inactive                   ((t (:background "#1a1a1a" :foreground "#4d4d4d"))))

 '(menu                                   ((t (:foreground "#2288ff"))))

 '(epe-dir-face                           ((t (:foreground "#44aa22"))))
 '(deft-title-face                        ((t (:foreground "#ff00ff" :weight bold))))
 '(highlight-context-line-face            ((t (:background "#292929"))))
 '(sp-pair-overlay-face                   ((t nil)))
 )
(provide-theme 'blackbored)
;;; blackbored-theme.el ends here
