;;; blackbored-theme --- pretty colours
;;; Commentary:
;;; Code:
(deftheme blackbored)
(custom-theme-set-faces
 'blackbored
 '(default                                ((t (:background "Black" :foreground "white"))))
 '(mode-line                              ((t (:background "gray20" :foreground "#20d030"))))
 '(mode-line-inactive                     ((t (:background "gray10" :foreground "gray30"))))
 '(hl-line                                ((t (:background "#151515"))))
 '(diary                                  ((t (:foreground "orange"))))
 '(font-lock-builtin-face                 ((t (:foreground "#4c83ff"))))
 '(font-lock-comment-face                 ((t (:foreground "#8a8a8a"))))
 '(font-lock-constant-face                ((t (:foreground "#D8FA3C"))))
 '(font-lock-doc-string-face              ((t (:foreground "Darkorange"))))
 '(font-lock-function-name-face           ((t (:foreground "magenta"))))
 '(font-lock-keyword-face                 ((t (:foreground "#FBDE2D"))))
 '(font-lock-preprocessor-face            ((t (:foreground "gray57"))))
 '(font-lock-reference-face               ((t (:foreground "gray"))))
 '(font-lock-regexp-grouping-backslash    ((t (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct    ((t (:foreground "red"))))
 '(font-lock-string-face                  ((t (:foreground "#61CE3C"))))
 '(font-lock-type-face                    ((t (:foreground "#E00000"))))
 '(font-lock-variable-name-face           ((t (:foreground "#FF6400"))))
 '(font-lock-warning-face                 ((t (:foreground "Pink"))))
 '(font-lock-doc-face                     ((t (:foreground "#61CE3C"))))
 '(region                                 ((t (:background "#7F073F"))))
 '(ivy-current-match                      ((t (:background "gray40"))))
 '(popup-face                             ((t (:background "#303030" :foreground "yellow"))))
 '(popup-tip-face                         ((t (:background "#303030" :foreground "#20d020"))))
 '(flycheck-info                          ((t (:underline  "pink"))))
 '(highlight-indent-guides-character-face ((t (:foreground "brightblack"))))
 '(term-color-blue                        ((t (:background "brightblue" :foreground "brightblue"))))
 '(term-color-red                         ((t (:background "red" :foreground "red"))))
 '(show-paren-match                       ((t (:background "gray24"))))
 '(widget-field                           ((t (:background "gray13" :foreground "#ff00ff"))))
 '(bookmark-face                          ((t (:background "darkslategray"))))
 '(lsp-face-highlight-textual             ((t (:background "#204030"))))
 '(secondary-selection                    ((t (:extend t :background "gray16"))))
 '(custom-button                          ((t (
                                               :background "#606060"
                                               :foreground "black"
                                               :box (:line-width (2 . 2) :style released-button)))))
 
 '(rainbow-delimiters-depth-1-face        ((t (:foreground "red"))))
 '(rainbow-delimiters-depth-2-face        ((t (:foreground "dark green"))))
 '(rainbow-delimiters-depth-3-face        ((t (:foreground "deep pink"))))
 '(rainbow-delimiters-depth-4-face        ((t (:foreground "yellow"))))
 '(rainbow-delimiters-depth-5-face        ((t (:foreground "green"))))
 '(rainbow-delimiters-depth-6-face        ((t (:foreground "light blue"))))
 '(rainbow-delimiters-depth-7-face        ((t (:foreground "orange"))))
 '(rainbow-delimiters-depth-8-face        ((t (:foreground "slate blue"))))
 '(rainbow-delimiters-depth-9-face        ((t (:foreground "light gray"))))
 '(rainbow-delimiters-unmatched-face      ((t (:foreground "white"))))

 '(org-level-1                            ((t (:foreground "#80ff00"))))
 '(org-level-2                            ((t (:foreground "#70e000"))))
 '(org-level-3                            ((t (:foreground "#60d000"))))
 '(org-level-4                            ((t (:foreground "#50c800"))))
 '(org-level-5                            ((t (:foreground "#40b000"))))
 '(org-level-6                            ((t (:foreground "#30a000"))))
 '(org-level-7                            ((t (:foreground "#209000"))))
 '(org-level-8                            ((t (:foreground "#108000"))))
 '(org-meta-line                          ((t (:foreground "gray30"))))

 '(visible-mark-active                    ((t (:background "#d0ffd0"))))
 '(visible-mark-face1                     ((t (:background "#80ff00"))))
 '(visible-mark-face2                     ((t (:background "#70a000"))))
 '(visible-mark-face3                     ((t (:background "#609000"))))
 '(visible-mark-face4                     ((t (:background "#507000"))))
 '(visible-mark-face5                     ((t (:background "#405000"))))
 '(visible-mark-face6                     ((t (:background "#305000"))))
 '(visible-mark-face7                     ((t (:background "#205020"))))
 '(visible-mark-face8                     ((t (:background "#104020"))))

 '(sp-pair-overlay-face                   ((t nil)))
 )
(provide-theme 'blackbored)
;;; blackbored-theme.el ends here
